/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import dto.ClientDto;
import projgl.db.dbControl;

/**
 *
 * @author lemmo
 */
public class AddClient extends javax.swing.JFrame {

    /**
     * Creates new form Ajclient2
     */
    public AddClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        tfPrenom = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        tfProfession = new javax.swing.JTextField();
        cbMoral = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfDesignation = new javax.swing.JTextField();
        tfAct = new javax.swing.JTextField();
        tfNRC = new javax.swing.JTextField();
        tfNIF = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        tfEmail = new javax.swing.JTextField();
        tfTel = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajouter client");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 280, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 50, -1));

        tfNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomActionPerformed(evt);
            }
        });
        tfNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNomKeyTyped(evt);
            }
        });
        getContentPane().add(tfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 80, -1));

        tfPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrenomActionPerformed(evt);
            }
        });
        tfPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrenomKeyTyped(evt);
            }
        });
        getContentPane().add(tfPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 80, -1));
        getContentPane().add(tfDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 80, -1));

        tfProfession.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfProfessionKeyTyped(evt);
            }
        });
        getContentPane().add(tfProfession, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 80, -1));

        cbMoral.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbMoral.setForeground(new java.awt.Color(255, 255, 255));
        cbMoral.setText("Personne morale");
        cbMoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMoralActionPerformed(evt);
            }
        });
        getContentPane().add(cbMoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prénom");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date de naissance");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Profession");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Designation");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Activiter");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("N° de registre de commerce");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("N° d’immatriculation fiscale.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        tfDesignation.setEditable(false);
        tfDesignation.setBackground(new java.awt.Color(255, 255,255,80));
        getContentPane().add(tfDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 130, -1));

        tfAct.setEditable(false);
        tfAct.setBackground(new java.awt.Color(255, 255, 255,80));
        tfAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActActionPerformed(evt);
            }
        });
        getContentPane().add(tfAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 130, -1));

        tfNRC.setEditable(false);
        tfNRC.setBackground(new java.awt.Color(255, 255, 255,80));
        getContentPane().add(tfNRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 130, -1));

        tfNIF.setEditable(false);
        tfNIF.setBackground(new java.awt.Color(255, 255, 255,80));
        getContentPane().add(tfNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 130, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 102));
        btnAdd.setText("Ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 120, 40));

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(0, 0, 102));
        btnReturn.setText("< Retourner");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 80, -1));

        tfTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelActionPerformed(evt);
            }
        });
        getContentPane().add(tfTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 80, -1));
        getContentPane().add(tfAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 80, -1));

        jLabel11.setText("Adresse");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel12.setText("Telephone");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Study\\L3\\GL\\Projet\\Code\\projGL\\src\\screens\\banka.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1300, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelActionPerformed

    private void tfNomActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfNomActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfNomActionPerformed

    private void tfPrenomActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfPrenomActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfPrenomActionPerformed

    private void cbMoralActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbMoralActionPerformed
        // TODO add your handling code here:
        boolean checkboxSelected = cbMoral.isSelected();

        // Rendre les textfields non modifiables si la case est cochée, sinon les rendre
        // modifiables

        tfDesignation.setEditable(checkboxSelected);
        tfAct.setEditable(checkboxSelected);
        tfNRC.setEditable(checkboxSelected);
        tfNIF.setEditable(checkboxSelected);

        tfDesignation.setOpaque(checkboxSelected);
        tfAct.setOpaque(checkboxSelected);
        tfNRC.setOpaque(checkboxSelected);
        tfNIF.setOpaque(checkboxSelected);

        // Redessinez le composant pour refléter les changements
        tfDesignation.repaint();
        tfAct.repaint();
        tfNRC.repaint();
        tfNIF.repaint();
    }// GEN-LAST:event_cbMoralActionPerformed

    private void tfActActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfActActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfActActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
        banquier1 a = new banquier1();
        a.show();
        dispose();
    }// GEN-LAST:event_btnReturnActionPerformed

    private void tfNomKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tfNomKeyTyped
        char Testchar = evt.getKeyChar();
        if (!((Character.isAlphabetic(Testchar))))
            evt.consume();
    }// GEN-LAST:event_tfNomKeyTyped

    private void tfPrenomKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tfPrenomKeyTyped
        char Testchar = evt.getKeyChar();
        if (!((Character.isAlphabetic(Testchar))))
            evt.consume();
    }// GEN-LAST:event_tfPrenomKeyTyped

    private void tfProfessionKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tfProfessionKeyTyped
        char Testchar = evt.getKeyChar();
        if (!((Character.isAlphabetic(Testchar))))
            evt.consume();
    }// GEN-LAST:event_tfProfessionKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        //get the values from the textfields
        String nom = tfNom.getText();
        String prenom = tfPrenom.getText();
        String date = tfDate.getText();
        String profession = tfProfession.getText();
        String designation = tfDesignation.getText();
        String act = tfAct.getText();
        String nrc = tfNRC.getText();
        String nif = tfNIF.getText();
        boolean isPhysic = cbMoral.isSelected();
        String address = tfAdress.getText();
        String tel = tfTel.getText();
        String email = tfEmail.getText();

        if (nom.isEmpty() || prenom.isEmpty() || date.isEmpty() || profession.isEmpty() || address.isEmpty()
                || tel.isEmpty() || email.isEmpty()) {
            // Show error message
            javax.swing.JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "Erreur",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } else if (isPhysic && (designation.isEmpty() || act.isEmpty() || nrc.isEmpty() || nif.isEmpty())) {
            // Show error message
            javax.swing.JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "Erreur",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            // Add the client to the database
            dbControl db = new dbControl();
            ClientDto c = new ClientDto(0, address, tel, email, !isPhysic, nom, prenom, date, profession, designation,
                    act, nrc, nif);
            db.insertClient(c);
            // Show success message
            javax.swing.JOptionPane.showMessageDialog(null, "Client ajouté avec succès", "Succès",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Return to the previous screen
            banquier1 a = new banquier1();
            a.setVisible(true);
            dispose();
        }

    }// GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReturn;
    private javax.swing.JCheckBox cbMoral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfAct;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfDesignation;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNIF;
    private javax.swing.JTextField tfNRC;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    private javax.swing.JTextField tfProfession;
    private javax.swing.JTextField tfTel;
    // End of variables declaration//GEN-END:variables
}
