/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.table.DefaultTableModel;

import dto.CompteDto;
import projgl.db.dbControl;
import javax.swing.JOptionPane;

/**
 *
 * @author lemmo
 */
public class cl1 extends javax.swing.JFrame {

    /**
     * Creates new form cl1
     */
    public cl1(int idClient) {

        initComponents();
        this.idClient = idClient;
        db = new dbControl();
        model = new DefaultTableModel();
        tableCompte.setModel(model);
        model.addColumn("Numero");
        model.addColumn("date d'ouverture");
        model.addColumn("Type");
        model.addColumn("Max");
        refresh();
    }
    DefaultTableModel model;
    dbControl db;
    final int idClient;
    // ArrayList<CompteDto> comptes;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelect = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        tableCompte = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSelect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(0, 0, 102));
        btnSelect.setText("selectioner un compte");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        tableCompte.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Numero", "Client", "Date d'ouverture", "Solde"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        scroll.setViewportView(tableCompte);

        background
                .setIcon(new javax.swing.ImageIcon("C:\\Study\\L3\\GL\\Projet\\Code\\projGL\\src\\screens\\bank3.png")); // NOI18N
        background.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 750, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(380, 380, 380)
                                                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(430, 430, 430)
                                                        .addComponent(btnSelect))
                                                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 750,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(90, 90, 90)
                                                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSelectActionPerformed
        // Get the selected row count
        int selectedRowCount = tableCompte.getSelectedRowCount();

        // Confirm that one row is selected, not more, not less
        if (selectedRowCount != 1) {
            // If no row is selected or more than one row is selected, show a message
            // ...

            if (selectedRowCount != 1) {
                // If no row is selected or more than one row is selected, show a message box
                JOptionPane.showMessageDialog(this, "Please select exactly one row to continue.");
            }
        } else {
            // Get the selected row index
            int rowIndex = tableCompte.getSelectedRow();
            System.out.println("Selected Row Index: " + rowIndex);
            //get the selected row's idCompte
            int idCompte = (int) tableCompte.getValueAt(rowIndex, 0);
            //go to Client2 screen
            Historique c2 = new Historique(idCompte);
            c2.setVisible(true);
            // dispose();
        }

    }// GEN-LAST:event_btnSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cl1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cl1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cl1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cl1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new cl1().setVisible(true);
            }
        });
    }

    private void refresh() {
        var comptes = db.findAllCompte(idClient);

        // for (int i = 0; i < comptes.size(); i++) {
        // tableCompte.setValueAt(comptes.get(i).getNumero(), i, 0);
        // tableCompte.setValueAt(comptes.get(i).getIdClient(), i, 1);
        // tableCompte.setValueAt(comptes.get(i).getDateOuverture(), i, 2);
        // tableCompte.setValueAt(comptes.get(i).getSolde(), i, 3);
        // }

        
        // set the tableCompte's data from comptes.
        
        

        // model.addColumn("solde");

        // set the tableCompte's row data
        for (CompteDto compte : comptes) {
            model.addRow(new Object[] {
                    compte.getIdCompte(),
                    compte.getDate(),
                    // compte.getSolde(),
                    compte.getType(),
                    compte.getMax()
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnSelect;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tableCompte;
    // End of variables declaration//GEN-END:variables
}
