/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.table.DefaultTableModel;

import projgl.tableType;
import projgl.db.dbControl;

/**
 *
 * @author HP
 */
public class Clients extends javax.swing.JFrame {

    /**
     * Creates new form banquier1
     */
    public Clients() {
        initComponents();
        modelPhy = new DefaultTableModel();
        tableClientsPhysic.setModel(modelPhy);
        modelPhy.addColumn("Matricule");
        modelPhy.addColumn("Nom");
        modelPhy.addColumn("Prenom");
        modelPhy.addColumn("Date de naissance");
        modelPhy.addColumn("Adresse");
        modelPhy.addColumn("Telephone");
        modelPhy.addColumn("Email");
        modelPhy.addColumn("Profession");

        modelMor = new DefaultTableModel();
        jTable1.setModel(modelMor);
        modelMor.addColumn("Raison sociale");
        modelMor.addColumn("Secteur d'activite");
        modelMor.addColumn("N° RC");
        modelMor.addColumn("N° MF");

        // model.addColumn("Matricule");
        refresh();

    }

    dbControl dbc = new dbControl();
    DefaultTableModel modelPhy;
    DefaultTableModel modelMor;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddClient = new java.awt.Button();
        btnSelect = new java.awt.Button();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClientsPhysic = new javax.swing.JTable();
        cbAffichage = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddClient.setBackground(new java.awt.Color(255, 255, 255));
        btnAddClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddClient.setLabel("Ajouter un  client");
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 170, 30));

        btnSelect.setBackground(new java.awt.Color(255, 255, 255));
        btnSelect.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSelect.setLabel("Selectionner un client\n");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 180, 30));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("supprimer client");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 180, 30));

        tableClientsPhysic.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Matricule", "Nom", "Prenom", "Date de naissance"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableClientsPhysic);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 530, 370));

        cbAffichage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physic", "Moral" }));
        cbAffichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAffichageActionPerformed(evt);
            }
        });
        getContentPane().add(cbAffichage, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "designation", "activiter", "N° RC", "N° MF"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 480, 370));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/screens/banka.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1300, 630));

        setSize(new java.awt.Dimension(1316, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddClientActionPerformed
        AddClient a = new AddClient();
        a.show();
        dispose(); 
    }// GEN-LAST:event_btnAddClientActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        int id = selectedID();
        if (id == -1) {
            return;
        }

        //ask the user to confirm deletion
        int response = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this row?",
                "Confirm", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

        //if the user confirmed deletion
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            //delete the row from the database
            dbc.delete(id, tableType.client);
            //refresh the table
            refresh();
        }


    }// GEN-LAST:event_btnDeleteActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSelectActionPerformed
        int id = selectedID();
        // System.out.println(selected);

        if (id == -1) {
            return;
        }

        // int id = (int) tableClientsPhysic.getValueAt(selected, 0);
        Comptes c = new Comptes(id);
        c.show();
        dispose();

    }// GEN-LAST:event_btnSelectActionPerformed

    private void cbAffichageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbAffichageActionPerformed
        refresh();

    }// GEN-LAST:event_cbAffichageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clients().setVisible(true);
            }
        });
    }

    private void refresh() {
        int index = cbAffichage.getSelectedIndex();

        switch (index) {
            case 0:
                afficherClientsPhysic();
                break;
            case 1:
                afficherClientsMoral();
                break;
            default:
                break;
        }

    }

    private void afficherClientsPhysic() {
        modelPhy.setRowCount(0);
        modelMor.setRowCount(0);

        var list = dbc.findAllClient();
        for (var c : list) {
            if (c.isPhysic) {
                modelPhy.addRow(new Object[] { c.getIdClient(), c.getNom(), c.getPrenom(), c.getDate(), c.getAddress(),
                        c.getTel(), c.getEmail(), c.getProfession() });
            }

        }
    }

    private void afficherClientsMoral() {
        modelPhy.setRowCount(0);
        modelMor.setRowCount(0);
        var list = dbc.findAllClient();
        for (var c : list) {
            if (!c.isPhysic) {
                modelPhy.addRow(new Object[] { c.getIdClient(), c.getNom(), c.getPrenom(), c.getDate(), c.getAddress(),
                        c.getTel(), c.getEmail(), c.getProfession() });
                modelMor.addRow(new Object[] { c.getDesignation(), c.getActiviter(), c.getNrc(),
                        c.getNif() });
            }

        }

    }

    private int selectedID()
    {
        //verify that exactly one row is selected
        int row = tableClientsPhysic.getSelectedRow();        
        if (row == -1 || tableClientsPhysic.getSelectedRowCount() != 1) {
            //show error message to the user in a dialog
            javax.swing.JOptionPane.showMessageDialog(this, "Please select exactly one row to delete!");
            return -1;
        }

        //get the selected row's id
        return (int) tableClientsPhysic.getValueAt(row, 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAddClient;
    private javax.swing.JButton btnDelete;
    private java.awt.Button btnSelect;
    private javax.swing.JComboBox<String> cbAffichage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableClientsPhysic;
    // End of variables declaration//GEN-END:variables
}
