/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.table.DefaultTableModel;

import dto.CompteDto;
import projgl.db.dbControl;

//import screens.banquier1;
/**
 *
 * @author HP
 */
public class Comptes extends javax.swing.JFrame {

    /**
     * Creates new form Comptes
     */
    public Comptes(int idClient) {
        initComponents();
        this.idClient = idClient;
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Numero");
        model.addColumn("Date de creation");
        model.addColumn("Solde");
        model.addColumn("Type");
        model.addColumn("Max");
        refresh();
    }

    private void refresh() {
        var comptes = db.findAllCompte(idClient);
        model.setRowCount(0);
        for (var compte : comptes) {
            model.addRow(new Object[] {
                compte.getIdCompte(),
                compte.getDate(),
                compte.getSolde(),
                compte.getType(),
                compte.getMax()
            });
        }
    }

    DefaultTableModel model;
    dbControl db = new dbControl();
    int idClient;
    CompteDto currentCompte;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelect = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnValidate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnReturn = new javax.swing.JButton();
        tfDebCred = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSolde = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(0, 0, 102));
        btnSelect.setText("Selectioner un compte");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 0, 102));
        btnCreate.setText("Crée compte");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        btnValidate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValidate.setForeground(new java.awt.Color(0, 0, 102));
        btnValidate.setText("Valider");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 80, 30));

        jTextPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane2.setForeground(new java.awt.Color(0, 0, 102));
        jTextPane2.setText("Solde");
        jScrollPane4.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jTextPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 0, 102));
        jTextPane1.setText("Entrer le montant que le client souhaite débiter ou créditer");
        jScrollPane3.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(0, 0, 102));
        btnReturn.setText("< Retourner ");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));
        getContentPane().add(tfDebCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 90, -1));

        taSolde.setColumns(20);
        taSolde.setRows(5);
        jScrollPane2.setViewportView(taSolde);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "numero", "Client", "Date d'ouverture", "Solde"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 390, 160));

        btnDelete.setText("Suprimer Compte");
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Study\\L3\\GL\\Projet\\Code\\projGL\\src\\screens\\banka.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 628));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        //try get the value from the text field as an integer
        double montant;
        try {
            montant = Double.parseDouble(tfDebCred.getText());
        } catch (NumberFormatException e) {
            //show error message to the user in a dialog
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number.");
            return;
        }

        //verify that a Compte is selected
        if (currentCompte == null) {
            //show error message to the user in a dialog
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a Compte.");
            return;
        }

        System.out.println("montant: " + montant);
        if (montant < 0) {
            boolean success = currentCompte.debiter(-montant);
            if (!success) {
                //show error message to the user in a dialog
                javax.swing.JOptionPane.showMessageDialog(this, "The Compte does not have enough money.");
            }
            else
            {
                tfDebCred.setText("");
            }
        }
        else {
            currentCompte.crediter(montant);
            tfDebCred.setText("");
        }

        refresh();
        
    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        AddCompte a = new AddCompte(idClient);
        a.show();
        dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        Clients a = new Clients();
        a.show();
        dispose(); 
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        //get selected row
        int row = jTable1.getSelectedRow();
        //verify that exactly one row is selected
        if (row == -1 || jTable1.getSelectedRowCount() != 1) {
            //show error message to the user in a dialog
            javax.swing.JOptionPane.showMessageDialog(this, "Please select exactly one row to edit.");
            return;
        }

        //get the selected Compte
        int idCompte = (int) jTable1.getValueAt(row, 0);
        currentCompte = db.findCompte(idCompte);

        taSolde.setText(String.valueOf(currentCompte.getSolde()));
        
    }//GEN-LAST:event_btnSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comptes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Comptes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnValidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextArea taSolde;
    private javax.swing.JTextField tfDebCred;
    // End of variables declaration//GEN-END:variables
}
